name: effective_avangers
description: A new Flutter project.


publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  card_swiper: ^2.0.4
  cached_network_image: 
  dio: ^4.0.6
  
  drift: ^2.2.0
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.0.0
  path: 
  crypto: ^3.0.2
  flutter_dotenv: ^5.0.2
  flutter_riverpod: ^2.1.1



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  drift_dev: ^2.2.0+1
  build_runner: ^2.2.1
  
flutter:

  uses-material-design: true
  assets:
    - lib/src/images/marvel.png
    - .env

 
