name: effective_avangers
description: A new Flutter project.


publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  card_swiper: ^2.0.4
  cached_network_image: 
  dio: ^4.0.6
  palette_generator: ^0.3.3+2 
  drift: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  assets:
    - lib/images/marvel.png

 
